# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0029_auto_20171205_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='评论者名字')),
                ('email', models.EmailField(max_length=255, verbose_name='评论者邮箱')),
                ('url', models.URLField(blank=True, verbose_name='评论者链接')),
                ('text', models.TextField(verbose_name='评论内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='评论发表时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='评论所属文章')),
            ],
        ),
    ]
