# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_textlist_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_body', models.TextField()),
                ('blog_category', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='textlist',
        ),
    ]
