# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171124_1451'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_body', models.TextField()),
                ('blog_category', models.CharField(max_length=15)),
                ('blog_date', models.DateTimeField(verbose_name='申请时间')),
                ('blog_about', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='comments',
        ),
    ]
