# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 07:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171124_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_comments',
            new_name='comments',
        ),
    ]
