# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20171124_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='blog_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存时间'),
        ),
    ]
