# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171125_1113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='b_comments',
            new_name='comments',
        ),
    ]
