# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20171128_0953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='commenta',
            new_name='comments',
        ),
    ]
