# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20171128_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
