# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20171128_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='blog_label',
        ),
    ]
