# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_remove_comments_blog_label'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comments',
            new_name='article',
        ),
    ]
