# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20171130_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='category',
            name='update_date',
        ),
    ]
