# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_auto_20171201_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.AlterField(
            model_name='article',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='blog_tags',
            field=models.ManyToManyField(blank=True, to='blog.Tags'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
