# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20171205_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='blog_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='blog_tags',
            field=models.ManyToManyField(blank=True, to='blog.Tags'),
        ),
    ]
